// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html
//       lang="en"
//       className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
//     >
//       <body className="min-h-full flex flex-col">{children}</body>
//     </html>
//   );
// }

import './globals.css'; // Твои глобальные стили и Tailwind
import { Playfair_Display, Inter } from 'next/font/google';
import Link from 'next/link';
import { FaTelegram, FaInstagram, FaYoutube, FaTiktok, FaPinterest, FaFacebook } from 'react-icons/fa6';

const playfair = Playfair_Display({
  subsets: ['cyrillic', 'latin'],
  variable: '--font-playfair',
});

const inter = Inter({
  subsets: ['cyrillic', 'latin'],
  variable: '--font-inter',
});

export const metadata = {
  title: 'LoraDei — Бережная психотерапия',
  description: 'Расстановки на МАК-картах, регресс и телесно-ориентированная терапия.',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ru" className={`${inter.variable} ${playfair.variable}`}>
      <body className="bg-psy-bg text-psy-textMain font-sans antialiased min-h-screen flex flex-col items-center w-full overflow-x-hidden">
        
        {/* ВЕРХНИЙ АПП-БАР (Теперь один на весь сайт) */}
        <header className="fixed top-0 left-0 right-0 z-50 w-full border-b border-psy-textMuted/10 bg-psy-bg/70 backdrop-blur-md px-6 py-4 md:px-[8%]">
          <div className="flex justify-between items-center max-w-7xl mx-auto w-full relative">
            <Link href="/" className="font-serif text-xl font-semibold tracking-wide text-psy-textMain z-50">
              LoraDei
            </Link>
            
            {/* ЧИСТЫЙ CSS БУРГЕР */}
            <input type="checkbox" id="menu-toggle" className="peer hidden" />
            
            <label htmlFor="menu-toggle" className="flex flex-col gap-1.5 cursor-pointer md:hidden z-50 p-1">
              <span className="w-6 h-0.5 bg-psy-textMain transition-all"></span>
              <span className="w-6 h-0.5 bg-psy-textMain transition-all"></span>
              <span className="w-6 h-0.5 bg-psy-textMain transition-all"></span>
            </label>

            {/* НАВИГАЦИЯ (Используем Link для мгновенных переходов) */}
            <nav className="
              absolute top-12 left-0 right-0 flex flex-col items-center gap-6 py-8 bg-psy-bg/95 backdrop-blur-lg border-b border-psy-textMuted/10 opacity-0 pointer-events-none transition-all duration-300
              peer-checked:opacity-100 peer-checked:pointer-events-auto
              md:static md:flex-row md:opacity-100 md:pointer-events-auto md:py-0 md:bg-transparent md:border-none md:space-x-9 md:space-y-0 md:gap-0
            ">
            <Link href="/about" className="text-sm text-psy-textMuted hover:text-psy-accent transition-colors">
              Обо мне
            </Link>
            <Link href="/constellations" className="text-sm text-psy-textMuted hover:text-psy-accent transition-colors">
              Расстановки
            </Link>
            <Link href="/regress" className="text-sm text-psy-textMuted hover:text-psy-accent transition-colors">
              Регресс
            </Link>
            <Link href="/somatic" className="text-sm text-psy-textMuted hover:text-psy-accent transition-colors">
              Телесная терапия
            </Link>
            <Link href="/contacts" className="text-sm text-psy-textMuted hover:text-psy-accent transition-colors">
              Контакты
            </Link>
            </nav>
          </div>
        </header>

        {/* СЮДА NEXT.JS БУДЕТ ПОДСТАВЛЯТЬ КОНТЕНТ КАЖДОЙ СТРАНИЦЫ */}
        <main className="w-full flex-grow flex flex-col items-center">
          {children}
        </main>

        {/* НИЖНИЙ АПП-БАР / ФУТЕР (Тоже один на весь сайт) */}
        <footer className="fixed bottom-0 left-0 right-0 z-50 w-full border-t border-psy-textMuted/10 bg-psy-bg/70 backdrop-blur-md px-6 py-4 md:px-[8%]">
          <div className="flex flex-col md:flex-row items-center md:justify-between max-w-7xl mx-auto gap-4 w-full">
            
            <div className="text-[11px] text-psy-textMuted tracking-wide order-2 md:order-1">
              © 2026 LoraDei. Все права защищены.
            </div>

            <div className="flex items-center justify-center gap-6 flex-wrap order-1 md:order-2">
               <a href="https://t.me/+QA7BY8kUwyA1YmU8" target="_blank" rel="noopener noreferrer" className="text-psy-textMuted hover:text-psy-accent transition-colors duration-200" aria-label="Telegram"><FaTelegram className="w-5 h-5" /></a>
            <a href="https://www.instagram.com/lora_dei?igsh=dDhiMjd0YnA5OW5u" target="_blank" rel="noopener noreferrer" className="text-psy-textMuted hover:text-psy-accent transition-colors duration-200" aria-label="Instagram"><FaInstagram className="w-5 h-5" /></a>
            <a href="https://www.tiktok.com/@lora.deineka8?_r=1&_t=ZN-96O6MD6WzWY" target="_blank" rel="noopener noreferrer" className="text-psy-textMuted hover:text-psy-accent transition-colors duration-200" aria-label="TikTok"><FaTiktok className="w-5 h-5" /></a>
            <a href="https://www.facebook.com/share/1AoDbT9774/?mibextid=wwXIfr" target="_blank" rel="noopener noreferrer" className="text-psy-textMuted hover:text-psy-accent transition-colors duration-200" aria-label="Facebook"><FaFacebook className="w-5 h-5" /></a>
            <a href="http://www.youtube.com/@loradei" target="_blank" rel="noopener noreferrer" className="text-psy-textMuted hover:text-psy-accent transition-colors duration-200" aria-label="YouTube"><FaYoutube className="w-5 h-5" /></a>
          </div>

          </div>
        </footer>

      </body>
    </html>
  );
}